#!/usr/bin/env python3
"""Build the dashboard dataset from the KIISE source CSV.

Reads ``data/excellent_sw_conferences_2024.csv`` and writes a browser-ready
``docs/assets/data.js`` that assigns ``window.KIISE_DATA``. Emitting a ``.js``
file (rather than JSON fetched at runtime) lets the dashboard open directly
from the filesystem as well as from GitHub Pages, with no fetch/CORS caveats.

Usage:
    python scripts/build_data.py
"""
from __future__ import annotations

import csv
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "excellent_sw_conferences_2024.csv"
OUT = ROOT / "docs" / "assets" / "data.js"

# Full names for the KIISE sub-field abbreviations (소분야).
SUBFIELD_NAMES = {
    "ML": "Machine Learning",
    "NLP": "Natural Language Processing",
    "CV": "Computer Vision",
    "Bio": "Bioinformatics",
    "Robot": "Robotics",
    "SE": "Software Engineering",
    "OS": "Operating Systems",
    "PL": "Programming Languages",
    "Sec": "Security",
    "CGI": "Computer Graphics / HCI",
    "DM": "Data Mining",
    "Net": "Networks",
    "Arch": "Computer Architecture",
    "Alg": "Algorithms / Theory",
    "DB": "Database",
    "HPC": "High Performance Computing",
}

MAJOR_NAMES = {
    "AI": "Artificial Intelligence",
    "CS": "Computer Science",
}


def build() -> dict:
    records: list[dict] = []
    deleted: list[dict] = []

    with SRC.open(encoding="utf-8-sig", newline="") as fh:
        reader = csv.reader(fh)
        header = next(reader)  # 번호,대분야,소분야,약칭,학회명,등급,비고
        for row in reader:
            if len(row) < 6:
                continue
            no, major, sub, abbr, name, grade = (c.strip() for c in row[:6])
            note = row[6].strip() if len(row) > 6 else ""

            # Rows without an abbreviation are continuation/blank lines.
            if not abbr:
                continue

            rec = {
                "no": no,
                "major": major,
                "sub": sub,
                "subName": SUBFIELD_NAMES.get(sub, sub),
                "abbr": abbr,
                "name": name,
                "grade": grade,
                "note": note,
            }

            # Deleted entries (삭제) have no 번호 — keep them separately.
            if not no or "삭제" in note:
                deleted.append(rec)
            else:
                records.append(rec)

    return {
        "records": records,
        "deleted": deleted,
        "majorNames": MAJOR_NAMES,
        "subfieldNames": SUBFIELD_NAMES,
        "source": "excellent_sw_conferences_2024.csv",
        "year": 2024,
    }


def main() -> None:
    data = build()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(data, ensure_ascii=False, indent=2)
    OUT.write_text(
        "// Auto-generated by scripts/build_data.py — do not edit by hand.\n"
        f"window.KIISE_DATA = {payload};\n",
        encoding="utf-8",
    )
    n = len(data["records"])
    s = sum(1 for r in data["records"] if r["grade"] == "S")
    a = sum(1 for r in data["records"] if r["grade"] == "A")
    print(f"Wrote {OUT.relative_to(ROOT)}: {n} conferences (S={s}, A={a}), "
          f"{len(data['deleted'])} deleted.")


if __name__ == "__main__":
    main()
